name: Inner Discipline

on:
  workflow_dispatch:
    inputs:
      script:
        description: "Which script to run"
        required: true
        default: "generate"
        type: choice
        options:
          - generate
          - promo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - run: pip install -r requirements.txt

      - name: Run generate.py
        if: ${{ github.event.inputs.script == 'generate' }}
        run: python generate.py

      - name: Run promo.py
        if: ${{ github.event.inputs.script == 'promo' }}
        run: python promo.py

      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/
